# Site settings
title: unreal4u's personal network
email: me@unreal4u.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.unreal4u.com" # the base hostname & protocol for your site
twitter_username: unreal4u
github_username:  unreal4u

# Build settings
markdown: kramdown
