# Site settings
title: unreal4u's personal network
email: me@unreal4u.com
description: > # this means to ignore newlines until "baseurl:"
  Because my reality... is just your virtuality
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.unreal4u.com" # the base hostname & protocol for your site
twitter_username: unreal4u
github_username:  unreal4u

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
permalink: /:year/:month/:title/
paginate: 15
paginate_path: "/page/:num/"

# SASS settings
sass:
  style: :compressed
  sass_dir: _sass
